2019-02-05 16:33:44,434 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 16:34:55,360 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 16:38:16,185 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 16:40:01,434 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 17:58:31,072 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 17:58:40,775 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print requests.POST
AttributeError: 'module' object has no attribute 'POST'
2019-02-05 17:58:45,478 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print requests.POST
AttributeError: 'module' object has no attribute 'POST'
2019-02-05 17:58:46,078 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print requests.POST
AttributeError: 'module' object has no attribute 'POST'
2019-02-05 17:58:46,225 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print requests.POST
AttributeError: 'module' object has no attribute 'POST'
2019-02-05 17:58:46,378 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print requests.POST
AttributeError: 'module' object has no attribute 'POST'
2019-02-05 17:58:56,757 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 17:59:21,757 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print request.POST
NameError: global name 'request' is not defined
2019-02-05 17:59:53,837 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view django_blog.django_blog.views.UserUpdateView didn't return an HttpResponse object. It returned None instead.
2019-02-05 18:07:35,847 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:07:45,480 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:08:31,352 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:08:39,237 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:09:03,509 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:09:05,667 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:09:11,405 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-05 18:21:13,901 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print self.request.files
AttributeError: 'WSGIRequest' object has no attribute 'files'
2019-02-05 18:21:17,622 [ERROR] django.request: Internal Server Error: /dashboard/user/edit/3/
Traceback (most recent call last):
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/mixins.py", line 28, in dispatch
    return super(AdminOnlyMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/Sreenivas/anaconda3/envs/blog/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Sreenivas/projects/sreenivas/blog/aitechcentral/django_blog/django_blog/views.py", line 535, in post
    print self.request.files
AttributeError: 'WSGIRequest' object has no attribute 'files'
2019-02-06 00:26:16,133 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:33,748 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:34,038 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:34,965 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:35,672 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:36,319 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:36,720 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:38,646 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:39,047 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:26:39,343 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:29:12,628 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:29:43,710 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:30:42,598 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:41:16,594 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:41:39,465 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:45:30,654 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:45:55,932 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:45:56,368 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:45:56,768 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:45:57,691 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:45:58,175 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:46:11,410 [WARNING] django.request: Not Found: /static/css/main.css.map
2019-02-06 00:46:55,426 [WARNING] django.request: Not Found: /static/css/main.css.map
